name: CI-Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  # Job for lint the repository
  linting:    
    runs-on: ubuntu-latest
    container: 
        image: sagemath/sagemath-dev:9.7
        options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Installing git and dependencies
      run: |
        echo $(sage -c "print(SAGE_ROOT)")
        ls -a $(sage -c "print(SAGE_ROOT)")/src
    - name: Linting code for repository
      run: |
        sage -tox -e relint -- pseries_basis

  style:    
    runs-on: ubuntu-latest
    container: 
        image: sagemath/sagemath-dev:9.7
        options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Checking pycodestyle-minimal
      run: |
        sage --version

  # Job for running the automatic tests in Sagemath
  testing:
    runs-on: ubuntu-latest
    container: 
        image: sagemath/sagemath-dev:9.7
        options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Installing git and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git apt-transport-https ca-certificates
        sudo apt-get clean
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Running sage tests
      run: |
        sage -tox -e doctest pseries_basis