name: Testing in Sage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: sagemath/sagemath:latest
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - uses: py-actions/py-dependency-install@v3
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Running sage tests
      run: |
        sage -t pseries_basis