name: Testing in Sage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    container: 
      image: sagemath/sagemath:9.3.beta8
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Installing git and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git apt-transport-https ca-certificates
        sudo apt-get clean
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Running sage tests
      run: |
        sage -t pseries_basis